### ISSUE TITLE
Felmeddelande vid checkout

### ISSUE THREAD

**Issue by philiplinell** [maya039/webshop#1]
Får följande felmeddelande:

```
Notice: Undefined variable: basket in /Users/philiplarson/Dropbox/Development/PHP/webshop/basket.php on line 63

Warning: Invalid argument supplied for foreach() in /Users/philiplarson/Dropbox/Development/PHP/webshop/basket.php on line 63

Notice: Undefined variable: itemresult in /Users/philiplarson/Dropbox/Development/PHP/webshop/basket.php on line 72

Notice: Undefined variable: itemresult in /Users/philiplarson/Dropbox/Development/PHP/webshop/basket.php on line 77
1 and
```

När jag gör följande:
1. Logga in
2. Klicka på Items
3. Lägg till 1 Java(s)
4. Klicka på basket
5. Klicka på Checkout
6. Klicka på Pay
7. Klicka på Basket
8. Klicka på Checkout

**Comment by AmyNgithub** [comment]
Fixat genom att Checkout knappen inte visas när basket är tom. Pushar upp detta nu. Ändrar även Pay till view receipt för att ta bort ev förvirring ^^

**Comment by AmyNgithub** [comment]
pushat nu. du kan väl kolla att det är löst på din sida också.

**Comment by philiplinell** [comment]
@AmyNgithub Funkar bra!
