### ISSUE TITLE
Checkout vid inte inloggad användare

### ISSUE THREAD

**Issue by philiplinell** [maya039/webshop#2]
```
Notice: Undefined index: username in /Users/philiplarson/Dropbox/Development/PHP/webshop/basket.php on line 44
```

Gör följande:
1. Klicka på Basket
2. Klicka på Checkout

**Comment by philiplinell** [comment]
Fixat via cefcbeb6c250fe9e0d3f5618e25ba8967f7b865b.

**Comment by AmyNgithub** [comment]
aha. Vi måste lägga in ett villkor i if-satsen som bestämmer om checkout knappen ska visas eller inte. 
Jag ska försöka fixa det

**Comment by philiplinell** [comment]
Nu visas den men klickar man på knappen händer inget. Håller med om att ett mer snyggt beteende vore om knappen inte syns när man inte är inloggad.

**Comment by AmyNgithub** [comment]
... jag har inte pushat upp någon ändring än. ska pusha upp den nu
